---
- name: Start terraform action
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: start tf file
      cloud.terraform.terraform:
        project_path: "{{ playbook_dir }}"
        state: present
        force_init: true